"""empty message

Revision ID: 725f2c6960cd
Revises: 99381175f30e
Create Date: 2022-05-23 05:58:14.523166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725f2c6960cd'
down_revision = '99381175f30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'verified')
    # ### end Alembic commands ###
