"""Allow languages to be managed on web client

Revision ID: 99381175f30e
Revises: 38e7afa4efe3
Create Date: 2022-05-23 03:27:21.084387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99381175f30e'
down_revision = '38e7afa4efe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('acive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codes', 'acive')
    # ### end Alembic commands ###
